### ISSUE TITLE
which protocol ?

### ISSUE THREAD

**Issue by tissatussa** [enoua5/revengechessII#35]
hi, your RevengeChess II does not seem to know any protocol like UCI or XBoard .. i think it's no use without it. For people to use your engine, you should implement such protocol, otherwise it's not realistic ..

**Comment by enoua5** [comment]
Hi, thanks for the question (and sorry I didn't see it for three weeks…). To answer the main confusion before the following ramble: Revenge Chess is more inspired by chess than actually being chess.

While I had considered using an existing engine protocol like UCI, I ultimately decided it wasn't really a priority for this project, and would probably only lead to unnecessary confusion-- using the RC II Core with a third party chess interface would leave me with no real way to communicate the full game state to the interface. Ultimately, while RC II contains a distinct core and computer player engine (RC Core + Vengence [sic apparently, spell check is only telling me this just now…]), the project itself is not a chess engine, nor is either the Core or Vengence-- it's a Revenge Chess engine.

I probably could have wrangled UCI into the project somehow, but I think it's 1) too late into the project where I'm now making small interface improvements (when I have time) to make the chage now, and 2) as mentioned earlier, wouldn't really add anything, as UCI-based UIs wouldn't know how to deal with the game.

That being said, If I were to start the project over now, I probably would have RC Core use something similar to UCI, even if just to make the UI not have to read the board state from a very non-portable WASM module, and/or the JSON interface the server uses (this is one of those projects where I've learned a lot from my mistakes, lol).

Anyway, sorry for rambling to you about all that. And, genuinely, thanks for showing interest in my little project!
